/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CitoyenneteRouteImport } from './routes/citoyennete'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as DemandeInscriptionRouteImport } from './routes/demande-inscription'
import { Route as EducationRouteImport } from './routes/education'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedDashboardEnseignantRouteImport } from './routes/_authenticated.dashboard-enseignant'
import { Route as AuthenticatedDashboardEtudiantRouteImport } from './routes/_authenticated.dashboard-etudiant'
import { Route as AuthenticatedEnseignantRouteImport } from './routes/_authenticated.enseignant'
import { Route as AuthenticatedEtablissementRouteImport } from './routes/_authenticated.etablissement'
import { Route as AuthenticatedEtudiantRouteImport } from './routes/_authenticated.etudiant'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminDemandesRouteImport } from './routes/_authenticated.admin.demandes'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated.admin.utilisateurs'
import { Route as AuthenticatedCoursesNewRouteImport } from './routes/_authenticated.courses.new'
import { Route as AuthenticatedEnseignantIndexRouteImport } from './routes/_authenticated.enseignant.index'
import { Route as AuthenticatedEnseignantEcoleRouteImport } from './routes/_authenticated.enseignant.ecole'
import { Route as AuthenticatedEnseignantElevesRouteImport } from './routes/_authenticated.enseignant.eleves'
import { Route as AuthenticatedEnseignantExamensRouteImport } from './routes/_authenticated.enseignant.examens'
import { Route as AuthenticatedEnseignantMediathequeRouteImport } from './routes/_authenticated.enseignant.mediatheque'
import { Route as AuthenticatedEnseignantMessagesRouteImport } from './routes/_authenticated.enseignant.messages'
import { Route as AuthenticatedEnseignantNotificationsRouteImport } from './routes/_authenticated.enseignant.notifications'
import { Route as AuthenticatedEnseignantParametresRouteImport } from './routes/_authenticated.enseignant.parametres'
import { Route as AuthenticatedEnseignantSyllabusRouteImport } from './routes/_authenticated.enseignant.syllabus'
import { Route as AuthenticatedEtablissementIndexRouteImport } from './routes/_authenticated.etablissement.index'
import { Route as AuthenticatedEtablissementAlertesRouteImport } from './routes/_authenticated.etablissement.alertes'
import { Route as AuthenticatedEtablissementClassesRouteImport } from './routes/_authenticated.etablissement.classes'
import { Route as AuthenticatedEtablissementCompositionRouteImport } from './routes/_authenticated.etablissement.composition'
import { Route as AuthenticatedEtablissementStatistiquesRouteImport } from './routes/_authenticated.etablissement.statistiques'
import { Route as AuthenticatedEtablissementUtilisateursRouteImport } from './routes/_authenticated.etablissement.utilisateurs'
import { Route as AuthenticatedEtablissementValidationContenusRouteImport } from './routes/_authenticated.etablissement.validation-contenus'
import { Route as AuthenticatedEtablissementValidationEnseignantsRouteImport } from './routes/_authenticated.etablissement.validation-enseignants'
import { Route as AuthenticatedEtudiantIndexRouteImport } from './routes/_authenticated.etudiant.index'
import { Route as AuthenticatedEtudiantAideRouteImport } from './routes/_authenticated.etudiant.aide'
import { Route as AuthenticatedEtudiantClassementRouteImport } from './routes/_authenticated.etudiant.classement'
import { Route as AuthenticatedEtudiantCoursRouteImport } from './routes/_authenticated.etudiant.cours'
import { Route as AuthenticatedEtudiantDefisRouteImport } from './routes/_authenticated.etudiant.defis'
import { Route as AuthenticatedEtudiantHistoriqueRouteImport } from './routes/_authenticated.etudiant.historique'
import { Route as AuthenticatedEtudiantMediathequeRouteImport } from './routes/_authenticated.etudiant.mediatheque'
import { Route as AuthenticatedEtudiantMessagesRouteImport } from './routes/_authenticated.etudiant.messages'
import { Route as AuthenticatedEtudiantNotificationsRouteImport } from './routes/_authenticated.etudiant.notifications'
import { Route as AuthenticatedEtudiantParametresRouteImport } from './routes/_authenticated.etudiant.parametres'
import { Route as AuthenticatedEtudiantRepresentationsRouteImport } from './routes/_authenticated.etudiant.representations'
import { Route as AuthenticatedEtudiantSujetsRouteImport } from './routes/_authenticated.etudiant.sujets'
import { Route as AuthenticatedEnseignantClassesIndexRouteImport } from './routes/_authenticated.enseignant.classes.index'
import { Route as AuthenticatedEnseignantClassesClassIdRouteImport } from './routes/_authenticated.enseignant.classes.$classId'
import { Route as AuthenticatedEtudiantCoursIndexRouteImport } from './routes/_authenticated.etudiant.cours.index'
import { Route as AuthenticatedEtudiantCoursProgrammeIdRouteImport } from './routes/_authenticated.etudiant.cours.$programmeId'
import { Route as AuthenticatedEtudiantExamensIndexRouteImport } from './routes/_authenticated.etudiant.examens.index'
import { Route as AuthenticatedEtudiantExamensExamenIdRouteImport } from './routes/_authenticated.etudiant.examens.$examenId'
import { Route as AuthenticatedEtudiantOrientationConseillerRouteImport } from './routes/_authenticated.etudiant.orientation.conseiller'
import { Route as AuthenticatedEtudiantOrientationFilieresRouteImport } from './routes/_authenticated.etudiant.orientation.filieres'
import { Route as AuthenticatedEtudiantOrientationMetiersRouteImport } from './routes/_authenticated.etudiant.orientation.metiers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CitoyenneteRoute = CitoyenneteRouteImport.update({
  id: '/citoyennete',
  path: '/citoyennete',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandeInscriptionRoute = DemandeInscriptionRouteImport.update({
  id: '/demande-inscription',
  path: '/demande-inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardEnseignantRoute =
  AuthenticatedDashboardEnseignantRouteImport.update({
    id: '/dashboard-enseignant',
    path: '/dashboard-enseignant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardEtudiantRoute =
  AuthenticatedDashboardEtudiantRouteImport.update({
    id: '/dashboard-etudiant',
    path: '/dashboard-etudiant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnseignantRoute = AuthenticatedEnseignantRouteImport.update({
  id: '/enseignant',
  path: '/enseignant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEtablissementRoute =
  AuthenticatedEtablissementRouteImport.update({
    id: '/etablissement',
    path: '/etablissement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEtudiantRoute = AuthenticatedEtudiantRouteImport.update({
  id: '/etudiant',
  path: '/etudiant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminDemandesRoute =
  AuthenticatedAdminDemandesRouteImport.update({
    id: '/demandes',
    path: '/demandes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCoursesNewRoute = AuthenticatedCoursesNewRouteImport.update({
  id: '/courses/new',
  path: '/courses/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnseignantIndexRoute =
  AuthenticatedEnseignantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEnseignantEcoleRoute =
  AuthenticatedEnseignantEcoleRouteImport.update({
    id: '/ecole',
    path: '/ecole',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEnseignantElevesRoute =
  AuthenticatedEnseignantElevesRouteImport.update({
    id: '/eleves',
    path: '/eleves',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEnseignantExamensRoute =
  AuthenticatedEnseignantExamensRouteImport.update({
    id: '/examens',
    path: '/examens',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEnseignantMediathequeRoute =
  AuthenticatedEnseignantMediathequeRouteImport.update({
    id: '/mediatheque',
    path: '/mediatheque',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEnseignantMessagesRoute =
  AuthenticatedEnseignantMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEnseignantNotificationsRoute =
  AuthenticatedEnseignantNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEnseignantParametresRoute =
  AuthenticatedEnseignantParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEnseignantSyllabusRoute =
  AuthenticatedEnseignantSyllabusRouteImport.update({
    id: '/syllabus',
    path: '/syllabus',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEtablissementIndexRoute =
  AuthenticatedEtablissementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEtablissementRoute,
  } as any)
const AuthenticatedEtablissementAlertesRoute =
  AuthenticatedEtablissementAlertesRouteImport.update({
    id: '/alertes',
    path: '/alertes',
    getParentRoute: () => AuthenticatedEtablissementRoute,
  } as any)
const AuthenticatedEtablissementClassesRoute =
  AuthenticatedEtablissementClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedEtablissementRoute,
  } as any)
const AuthenticatedEtablissementCompositionRoute =
  AuthenticatedEtablissementCompositionRouteImport.update({
    id: '/composition',
    path: '/composition',
    getParentRoute: () => AuthenticatedEtablissementRoute,
  } as any)
const AuthenticatedEtablissementStatistiquesRoute =
  AuthenticatedEtablissementStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedEtablissementRoute,
  } as any)
const AuthenticatedEtablissementUtilisateursRoute =
  AuthenticatedEtablissementUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedEtablissementRoute,
  } as any)
const AuthenticatedEtablissementValidationContenusRoute =
  AuthenticatedEtablissementValidationContenusRouteImport.update({
    id: '/validation-contenus',
    path: '/validation-contenus',
    getParentRoute: () => AuthenticatedEtablissementRoute,
  } as any)
const AuthenticatedEtablissementValidationEnseignantsRoute =
  AuthenticatedEtablissementValidationEnseignantsRouteImport.update({
    id: '/validation-enseignants',
    path: '/validation-enseignants',
    getParentRoute: () => AuthenticatedEtablissementRoute,
  } as any)
const AuthenticatedEtudiantIndexRoute =
  AuthenticatedEtudiantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantAideRoute =
  AuthenticatedEtudiantAideRouteImport.update({
    id: '/aide',
    path: '/aide',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantClassementRoute =
  AuthenticatedEtudiantClassementRouteImport.update({
    id: '/classement',
    path: '/classement',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantCoursRoute =
  AuthenticatedEtudiantCoursRouteImport.update({
    id: '/cours',
    path: '/cours',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantDefisRoute =
  AuthenticatedEtudiantDefisRouteImport.update({
    id: '/defis',
    path: '/defis',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantHistoriqueRoute =
  AuthenticatedEtudiantHistoriqueRouteImport.update({
    id: '/historique',
    path: '/historique',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantMediathequeRoute =
  AuthenticatedEtudiantMediathequeRouteImport.update({
    id: '/mediatheque',
    path: '/mediatheque',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantMessagesRoute =
  AuthenticatedEtudiantMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantNotificationsRoute =
  AuthenticatedEtudiantNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantParametresRoute =
  AuthenticatedEtudiantParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantRepresentationsRoute =
  AuthenticatedEtudiantRepresentationsRouteImport.update({
    id: '/representations',
    path: '/representations',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantSujetsRoute =
  AuthenticatedEtudiantSujetsRouteImport.update({
    id: '/sujets',
    path: '/sujets',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEnseignantClassesIndexRoute =
  AuthenticatedEnseignantClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEnseignantClassesClassIdRoute =
  AuthenticatedEnseignantClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AuthenticatedEnseignantRoute,
  } as any)
const AuthenticatedEtudiantCoursIndexRoute =
  AuthenticatedEtudiantCoursIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEtudiantCoursRoute,
  } as any)
const AuthenticatedEtudiantCoursProgrammeIdRoute =
  AuthenticatedEtudiantCoursProgrammeIdRouteImport.update({
    id: '/$programmeId',
    path: '/$programmeId',
    getParentRoute: () => AuthenticatedEtudiantCoursRoute,
  } as any)
const AuthenticatedEtudiantExamensIndexRoute =
  AuthenticatedEtudiantExamensIndexRouteImport.update({
    id: '/examens/',
    path: '/examens/',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantExamensExamenIdRoute =
  AuthenticatedEtudiantExamensExamenIdRouteImport.update({
    id: '/examens/$examenId',
    path: '/examens/$examenId',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantOrientationConseillerRoute =
  AuthenticatedEtudiantOrientationConseillerRouteImport.update({
    id: '/orientation/conseiller',
    path: '/orientation/conseiller',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantOrientationFilieresRoute =
  AuthenticatedEtudiantOrientationFilieresRouteImport.update({
    id: '/orientation/filieres',
    path: '/orientation/filieres',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)
const AuthenticatedEtudiantOrientationMetiersRoute =
  AuthenticatedEtudiantOrientationMetiersRouteImport.update({
    id: '/orientation/metiers',
    path: '/orientation/metiers',
    getParentRoute: () => AuthenticatedEtudiantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/citoyennete': typeof CitoyenneteRoute
  '/courses': typeof CoursesRouteWithChildren
  '/culture': typeof CultureRoute
  '/demande-inscription': typeof DemandeInscriptionRoute
  '/education': typeof EducationRoute
  '/inscription': typeof InscriptionRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard-enseignant': typeof AuthenticatedDashboardEnseignantRoute
  '/dashboard-etudiant': typeof AuthenticatedDashboardEtudiantRoute
  '/enseignant': typeof AuthenticatedEnseignantRouteWithChildren
  '/etablissement': typeof AuthenticatedEtablissementRouteWithChildren
  '/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/courses/new': typeof AuthenticatedCoursesNewRoute
  '/enseignant/ecole': typeof AuthenticatedEnseignantEcoleRoute
  '/enseignant/eleves': typeof AuthenticatedEnseignantElevesRoute
  '/enseignant/examens': typeof AuthenticatedEnseignantExamensRoute
  '/enseignant/mediatheque': typeof AuthenticatedEnseignantMediathequeRoute
  '/enseignant/messages': typeof AuthenticatedEnseignantMessagesRoute
  '/enseignant/notifications': typeof AuthenticatedEnseignantNotificationsRoute
  '/enseignant/parametres': typeof AuthenticatedEnseignantParametresRoute
  '/enseignant/syllabus': typeof AuthenticatedEnseignantSyllabusRoute
  '/etablissement/alertes': typeof AuthenticatedEtablissementAlertesRoute
  '/etablissement/classes': typeof AuthenticatedEtablissementClassesRoute
  '/etablissement/composition': typeof AuthenticatedEtablissementCompositionRoute
  '/etablissement/statistiques': typeof AuthenticatedEtablissementStatistiquesRoute
  '/etablissement/utilisateurs': typeof AuthenticatedEtablissementUtilisateursRoute
  '/etablissement/validation-contenus': typeof AuthenticatedEtablissementValidationContenusRoute
  '/etablissement/validation-enseignants': typeof AuthenticatedEtablissementValidationEnseignantsRoute
  '/etudiant/aide': typeof AuthenticatedEtudiantAideRoute
  '/etudiant/classement': typeof AuthenticatedEtudiantClassementRoute
  '/etudiant/cours': typeof AuthenticatedEtudiantCoursRouteWithChildren
  '/etudiant/defis': typeof AuthenticatedEtudiantDefisRoute
  '/etudiant/historique': typeof AuthenticatedEtudiantHistoriqueRoute
  '/etudiant/mediatheque': typeof AuthenticatedEtudiantMediathequeRoute
  '/etudiant/messages': typeof AuthenticatedEtudiantMessagesRoute
  '/etudiant/notifications': typeof AuthenticatedEtudiantNotificationsRoute
  '/etudiant/parametres': typeof AuthenticatedEtudiantParametresRoute
  '/etudiant/representations': typeof AuthenticatedEtudiantRepresentationsRoute
  '/etudiant/sujets': typeof AuthenticatedEtudiantSujetsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/enseignant/': typeof AuthenticatedEnseignantIndexRoute
  '/etablissement/': typeof AuthenticatedEtablissementIndexRoute
  '/etudiant/': typeof AuthenticatedEtudiantIndexRoute
  '/enseignant/classes/$classId': typeof AuthenticatedEnseignantClassesClassIdRoute
  '/etudiant/cours/$programmeId': typeof AuthenticatedEtudiantCoursProgrammeIdRoute
  '/etudiant/examens/$examenId': typeof AuthenticatedEtudiantExamensExamenIdRoute
  '/etudiant/orientation/conseiller': typeof AuthenticatedEtudiantOrientationConseillerRoute
  '/etudiant/orientation/filieres': typeof AuthenticatedEtudiantOrientationFilieresRoute
  '/etudiant/orientation/metiers': typeof AuthenticatedEtudiantOrientationMetiersRoute
  '/enseignant/classes/': typeof AuthenticatedEnseignantClassesIndexRoute
  '/etudiant/cours/': typeof AuthenticatedEtudiantCoursIndexRoute
  '/etudiant/examens/': typeof AuthenticatedEtudiantExamensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/citoyennete': typeof CitoyenneteRoute
  '/culture': typeof CultureRoute
  '/demande-inscription': typeof DemandeInscriptionRoute
  '/education': typeof EducationRoute
  '/inscription': typeof InscriptionRoute
  '/dashboard-enseignant': typeof AuthenticatedDashboardEnseignantRoute
  '/dashboard-etudiant': typeof AuthenticatedDashboardEtudiantRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/courses/new': typeof AuthenticatedCoursesNewRoute
  '/enseignant/ecole': typeof AuthenticatedEnseignantEcoleRoute
  '/enseignant/eleves': typeof AuthenticatedEnseignantElevesRoute
  '/enseignant/examens': typeof AuthenticatedEnseignantExamensRoute
  '/enseignant/mediatheque': typeof AuthenticatedEnseignantMediathequeRoute
  '/enseignant/messages': typeof AuthenticatedEnseignantMessagesRoute
  '/enseignant/notifications': typeof AuthenticatedEnseignantNotificationsRoute
  '/enseignant/parametres': typeof AuthenticatedEnseignantParametresRoute
  '/enseignant/syllabus': typeof AuthenticatedEnseignantSyllabusRoute
  '/etablissement/alertes': typeof AuthenticatedEtablissementAlertesRoute
  '/etablissement/classes': typeof AuthenticatedEtablissementClassesRoute
  '/etablissement/composition': typeof AuthenticatedEtablissementCompositionRoute
  '/etablissement/statistiques': typeof AuthenticatedEtablissementStatistiquesRoute
  '/etablissement/utilisateurs': typeof AuthenticatedEtablissementUtilisateursRoute
  '/etablissement/validation-contenus': typeof AuthenticatedEtablissementValidationContenusRoute
  '/etablissement/validation-enseignants': typeof AuthenticatedEtablissementValidationEnseignantsRoute
  '/etudiant/aide': typeof AuthenticatedEtudiantAideRoute
  '/etudiant/classement': typeof AuthenticatedEtudiantClassementRoute
  '/etudiant/defis': typeof AuthenticatedEtudiantDefisRoute
  '/etudiant/historique': typeof AuthenticatedEtudiantHistoriqueRoute
  '/etudiant/mediatheque': typeof AuthenticatedEtudiantMediathequeRoute
  '/etudiant/messages': typeof AuthenticatedEtudiantMessagesRoute
  '/etudiant/notifications': typeof AuthenticatedEtudiantNotificationsRoute
  '/etudiant/parametres': typeof AuthenticatedEtudiantParametresRoute
  '/etudiant/representations': typeof AuthenticatedEtudiantRepresentationsRoute
  '/etudiant/sujets': typeof AuthenticatedEtudiantSujetsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/enseignant': typeof AuthenticatedEnseignantIndexRoute
  '/etablissement': typeof AuthenticatedEtablissementIndexRoute
  '/etudiant': typeof AuthenticatedEtudiantIndexRoute
  '/enseignant/classes/$classId': typeof AuthenticatedEnseignantClassesClassIdRoute
  '/etudiant/cours/$programmeId': typeof AuthenticatedEtudiantCoursProgrammeIdRoute
  '/etudiant/examens/$examenId': typeof AuthenticatedEtudiantExamensExamenIdRoute
  '/etudiant/orientation/conseiller': typeof AuthenticatedEtudiantOrientationConseillerRoute
  '/etudiant/orientation/filieres': typeof AuthenticatedEtudiantOrientationFilieresRoute
  '/etudiant/orientation/metiers': typeof AuthenticatedEtudiantOrientationMetiersRoute
  '/enseignant/classes': typeof AuthenticatedEnseignantClassesIndexRoute
  '/etudiant/cours': typeof AuthenticatedEtudiantCoursIndexRoute
  '/etudiant/examens': typeof AuthenticatedEtudiantExamensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/citoyennete': typeof CitoyenneteRoute
  '/courses': typeof CoursesRouteWithChildren
  '/culture': typeof CultureRoute
  '/demande-inscription': typeof DemandeInscriptionRoute
  '/education': typeof EducationRoute
  '/inscription': typeof InscriptionRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard-enseignant': typeof AuthenticatedDashboardEnseignantRoute
  '/_authenticated/dashboard-etudiant': typeof AuthenticatedDashboardEtudiantRoute
  '/_authenticated/enseignant': typeof AuthenticatedEnseignantRouteWithChildren
  '/_authenticated/etablissement': typeof AuthenticatedEtablissementRouteWithChildren
  '/_authenticated/etudiant': typeof AuthenticatedEtudiantRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/demandes': typeof AuthenticatedAdminDemandesRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/courses/new': typeof AuthenticatedCoursesNewRoute
  '/_authenticated/enseignant/ecole': typeof AuthenticatedEnseignantEcoleRoute
  '/_authenticated/enseignant/eleves': typeof AuthenticatedEnseignantElevesRoute
  '/_authenticated/enseignant/examens': typeof AuthenticatedEnseignantExamensRoute
  '/_authenticated/enseignant/mediatheque': typeof AuthenticatedEnseignantMediathequeRoute
  '/_authenticated/enseignant/messages': typeof AuthenticatedEnseignantMessagesRoute
  '/_authenticated/enseignant/notifications': typeof AuthenticatedEnseignantNotificationsRoute
  '/_authenticated/enseignant/parametres': typeof AuthenticatedEnseignantParametresRoute
  '/_authenticated/enseignant/syllabus': typeof AuthenticatedEnseignantSyllabusRoute
  '/_authenticated/etablissement/alertes': typeof AuthenticatedEtablissementAlertesRoute
  '/_authenticated/etablissement/classes': typeof AuthenticatedEtablissementClassesRoute
  '/_authenticated/etablissement/composition': typeof AuthenticatedEtablissementCompositionRoute
  '/_authenticated/etablissement/statistiques': typeof AuthenticatedEtablissementStatistiquesRoute
  '/_authenticated/etablissement/utilisateurs': typeof AuthenticatedEtablissementUtilisateursRoute
  '/_authenticated/etablissement/validation-contenus': typeof AuthenticatedEtablissementValidationContenusRoute
  '/_authenticated/etablissement/validation-enseignants': typeof AuthenticatedEtablissementValidationEnseignantsRoute
  '/_authenticated/etudiant/aide': typeof AuthenticatedEtudiantAideRoute
  '/_authenticated/etudiant/classement': typeof AuthenticatedEtudiantClassementRoute
  '/_authenticated/etudiant/cours': typeof AuthenticatedEtudiantCoursRouteWithChildren
  '/_authenticated/etudiant/defis': typeof AuthenticatedEtudiantDefisRoute
  '/_authenticated/etudiant/historique': typeof AuthenticatedEtudiantHistoriqueRoute
  '/_authenticated/etudiant/mediatheque': typeof AuthenticatedEtudiantMediathequeRoute
  '/_authenticated/etudiant/messages': typeof AuthenticatedEtudiantMessagesRoute
  '/_authenticated/etudiant/notifications': typeof AuthenticatedEtudiantNotificationsRoute
  '/_authenticated/etudiant/parametres': typeof AuthenticatedEtudiantParametresRoute
  '/_authenticated/etudiant/representations': typeof AuthenticatedEtudiantRepresentationsRoute
  '/_authenticated/etudiant/sujets': typeof AuthenticatedEtudiantSujetsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/enseignant/': typeof AuthenticatedEnseignantIndexRoute
  '/_authenticated/etablissement/': typeof AuthenticatedEtablissementIndexRoute
  '/_authenticated/etudiant/': typeof AuthenticatedEtudiantIndexRoute
  '/_authenticated/enseignant/classes/$classId': typeof AuthenticatedEnseignantClassesClassIdRoute
  '/_authenticated/etudiant/cours/$programmeId': typeof AuthenticatedEtudiantCoursProgrammeIdRoute
  '/_authenticated/etudiant/examens/$examenId': typeof AuthenticatedEtudiantExamensExamenIdRoute
  '/_authenticated/etudiant/orientation/conseiller': typeof AuthenticatedEtudiantOrientationConseillerRoute
  '/_authenticated/etudiant/orientation/filieres': typeof AuthenticatedEtudiantOrientationFilieresRoute
  '/_authenticated/etudiant/orientation/metiers': typeof AuthenticatedEtudiantOrientationMetiersRoute
  '/_authenticated/enseignant/classes/': typeof AuthenticatedEnseignantClassesIndexRoute
  '/_authenticated/etudiant/cours/': typeof AuthenticatedEtudiantCoursIndexRoute
  '/_authenticated/etudiant/examens/': typeof AuthenticatedEtudiantExamensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/citoyennete'
    | '/courses'
    | '/culture'
    | '/demande-inscription'
    | '/education'
    | '/inscription'
    | '/admin'
    | '/dashboard-enseignant'
    | '/dashboard-etudiant'
    | '/enseignant'
    | '/etablissement'
    | '/etudiant'
    | '/auth/callback'
    | '/courses/$courseId'
    | '/courses/'
    | '/admin/demandes'
    | '/admin/utilisateurs'
    | '/courses/new'
    | '/enseignant/ecole'
    | '/enseignant/eleves'
    | '/enseignant/examens'
    | '/enseignant/mediatheque'
    | '/enseignant/messages'
    | '/enseignant/notifications'
    | '/enseignant/parametres'
    | '/enseignant/syllabus'
    | '/etablissement/alertes'
    | '/etablissement/classes'
    | '/etablissement/composition'
    | '/etablissement/statistiques'
    | '/etablissement/utilisateurs'
    | '/etablissement/validation-contenus'
    | '/etablissement/validation-enseignants'
    | '/etudiant/aide'
    | '/etudiant/classement'
    | '/etudiant/cours'
    | '/etudiant/defis'
    | '/etudiant/historique'
    | '/etudiant/mediatheque'
    | '/etudiant/messages'
    | '/etudiant/notifications'
    | '/etudiant/parametres'
    | '/etudiant/representations'
    | '/etudiant/sujets'
    | '/admin/'
    | '/enseignant/'
    | '/etablissement/'
    | '/etudiant/'
    | '/enseignant/classes/$classId'
    | '/etudiant/cours/$programmeId'
    | '/etudiant/examens/$examenId'
    | '/etudiant/orientation/conseiller'
    | '/etudiant/orientation/filieres'
    | '/etudiant/orientation/metiers'
    | '/enseignant/classes/'
    | '/etudiant/cours/'
    | '/etudiant/examens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/citoyennete'
    | '/culture'
    | '/demande-inscription'
    | '/education'
    | '/inscription'
    | '/dashboard-enseignant'
    | '/dashboard-etudiant'
    | '/auth/callback'
    | '/courses/$courseId'
    | '/courses'
    | '/admin/demandes'
    | '/admin/utilisateurs'
    | '/courses/new'
    | '/enseignant/ecole'
    | '/enseignant/eleves'
    | '/enseignant/examens'
    | '/enseignant/mediatheque'
    | '/enseignant/messages'
    | '/enseignant/notifications'
    | '/enseignant/parametres'
    | '/enseignant/syllabus'
    | '/etablissement/alertes'
    | '/etablissement/classes'
    | '/etablissement/composition'
    | '/etablissement/statistiques'
    | '/etablissement/utilisateurs'
    | '/etablissement/validation-contenus'
    | '/etablissement/validation-enseignants'
    | '/etudiant/aide'
    | '/etudiant/classement'
    | '/etudiant/defis'
    | '/etudiant/historique'
    | '/etudiant/mediatheque'
    | '/etudiant/messages'
    | '/etudiant/notifications'
    | '/etudiant/parametres'
    | '/etudiant/representations'
    | '/etudiant/sujets'
    | '/admin'
    | '/enseignant'
    | '/etablissement'
    | '/etudiant'
    | '/enseignant/classes/$classId'
    | '/etudiant/cours/$programmeId'
    | '/etudiant/examens/$examenId'
    | '/etudiant/orientation/conseiller'
    | '/etudiant/orientation/filieres'
    | '/etudiant/orientation/metiers'
    | '/enseignant/classes'
    | '/etudiant/cours'
    | '/etudiant/examens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/citoyennete'
    | '/courses'
    | '/culture'
    | '/demande-inscription'
    | '/education'
    | '/inscription'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard-enseignant'
    | '/_authenticated/dashboard-etudiant'
    | '/_authenticated/enseignant'
    | '/_authenticated/etablissement'
    | '/_authenticated/etudiant'
    | '/auth/callback'
    | '/courses/$courseId'
    | '/courses/'
    | '/_authenticated/admin/demandes'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/courses/new'
    | '/_authenticated/enseignant/ecole'
    | '/_authenticated/enseignant/eleves'
    | '/_authenticated/enseignant/examens'
    | '/_authenticated/enseignant/mediatheque'
    | '/_authenticated/enseignant/messages'
    | '/_authenticated/enseignant/notifications'
    | '/_authenticated/enseignant/parametres'
    | '/_authenticated/enseignant/syllabus'
    | '/_authenticated/etablissement/alertes'
    | '/_authenticated/etablissement/classes'
    | '/_authenticated/etablissement/composition'
    | '/_authenticated/etablissement/statistiques'
    | '/_authenticated/etablissement/utilisateurs'
    | '/_authenticated/etablissement/validation-contenus'
    | '/_authenticated/etablissement/validation-enseignants'
    | '/_authenticated/etudiant/aide'
    | '/_authenticated/etudiant/classement'
    | '/_authenticated/etudiant/cours'
    | '/_authenticated/etudiant/defis'
    | '/_authenticated/etudiant/historique'
    | '/_authenticated/etudiant/mediatheque'
    | '/_authenticated/etudiant/messages'
    | '/_authenticated/etudiant/notifications'
    | '/_authenticated/etudiant/parametres'
    | '/_authenticated/etudiant/representations'
    | '/_authenticated/etudiant/sujets'
    | '/_authenticated/admin/'
    | '/_authenticated/enseignant/'
    | '/_authenticated/etablissement/'
    | '/_authenticated/etudiant/'
    | '/_authenticated/enseignant/classes/$classId'
    | '/_authenticated/etudiant/cours/$programmeId'
    | '/_authenticated/etudiant/examens/$examenId'
    | '/_authenticated/etudiant/orientation/conseiller'
    | '/_authenticated/etudiant/orientation/filieres'
    | '/_authenticated/etudiant/orientation/metiers'
    | '/_authenticated/enseignant/classes/'
    | '/_authenticated/etudiant/cours/'
    | '/_authenticated/etudiant/examens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CitoyenneteRoute: typeof CitoyenneteRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  CultureRoute: typeof CultureRoute
  DemandeInscriptionRoute: typeof DemandeInscriptionRoute
  EducationRoute: typeof EducationRoute
  InscriptionRoute: typeof InscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citoyennete': {
      id: '/citoyennete'
      path: '/citoyennete'
      fullPath: '/citoyennete'
      preLoaderRoute: typeof CitoyenneteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demande-inscription': {
      id: '/demande-inscription'
      path: '/demande-inscription'
      fullPath: '/demande-inscription'
      preLoaderRoute: typeof DemandeInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-enseignant': {
      id: '/_authenticated/dashboard-enseignant'
      path: '/dashboard-enseignant'
      fullPath: '/dashboard-enseignant'
      preLoaderRoute: typeof AuthenticatedDashboardEnseignantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-etudiant': {
      id: '/_authenticated/dashboard-etudiant'
      path: '/dashboard-etudiant'
      fullPath: '/dashboard-etudiant'
      preLoaderRoute: typeof AuthenticatedDashboardEtudiantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enseignant': {
      id: '/_authenticated/enseignant'
      path: '/enseignant'
      fullPath: '/enseignant'
      preLoaderRoute: typeof AuthenticatedEnseignantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etablissement': {
      id: '/_authenticated/etablissement'
      path: '/etablissement'
      fullPath: '/etablissement'
      preLoaderRoute: typeof AuthenticatedEtablissementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/etudiant': {
      id: '/_authenticated/etudiant'
      path: '/etudiant'
      fullPath: '/etudiant'
      preLoaderRoute: typeof AuthenticatedEtudiantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/demandes': {
      id: '/_authenticated/admin/demandes'
      path: '/demandes'
      fullPath: '/admin/demandes'
      preLoaderRoute: typeof AuthenticatedAdminDemandesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/courses/new': {
      id: '/_authenticated/courses/new'
      path: '/courses/new'
      fullPath: '/courses/new'
      preLoaderRoute: typeof AuthenticatedCoursesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enseignant/': {
      id: '/_authenticated/enseignant/'
      path: '/'
      fullPath: '/enseignant/'
      preLoaderRoute: typeof AuthenticatedEnseignantIndexRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/enseignant/ecole': {
      id: '/_authenticated/enseignant/ecole'
      path: '/ecole'
      fullPath: '/enseignant/ecole'
      preLoaderRoute: typeof AuthenticatedEnseignantEcoleRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/enseignant/eleves': {
      id: '/_authenticated/enseignant/eleves'
      path: '/eleves'
      fullPath: '/enseignant/eleves'
      preLoaderRoute: typeof AuthenticatedEnseignantElevesRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/enseignant/examens': {
      id: '/_authenticated/enseignant/examens'
      path: '/examens'
      fullPath: '/enseignant/examens'
      preLoaderRoute: typeof AuthenticatedEnseignantExamensRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/enseignant/mediatheque': {
      id: '/_authenticated/enseignant/mediatheque'
      path: '/mediatheque'
      fullPath: '/enseignant/mediatheque'
      preLoaderRoute: typeof AuthenticatedEnseignantMediathequeRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/enseignant/messages': {
      id: '/_authenticated/enseignant/messages'
      path: '/messages'
      fullPath: '/enseignant/messages'
      preLoaderRoute: typeof AuthenticatedEnseignantMessagesRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/enseignant/notifications': {
      id: '/_authenticated/enseignant/notifications'
      path: '/notifications'
      fullPath: '/enseignant/notifications'
      preLoaderRoute: typeof AuthenticatedEnseignantNotificationsRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/enseignant/parametres': {
      id: '/_authenticated/enseignant/parametres'
      path: '/parametres'
      fullPath: '/enseignant/parametres'
      preLoaderRoute: typeof AuthenticatedEnseignantParametresRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/enseignant/syllabus': {
      id: '/_authenticated/enseignant/syllabus'
      path: '/syllabus'
      fullPath: '/enseignant/syllabus'
      preLoaderRoute: typeof AuthenticatedEnseignantSyllabusRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/etablissement/': {
      id: '/_authenticated/etablissement/'
      path: '/'
      fullPath: '/etablissement/'
      preLoaderRoute: typeof AuthenticatedEtablissementIndexRouteImport
      parentRoute: typeof AuthenticatedEtablissementRoute
    }
    '/_authenticated/etablissement/alertes': {
      id: '/_authenticated/etablissement/alertes'
      path: '/alertes'
      fullPath: '/etablissement/alertes'
      preLoaderRoute: typeof AuthenticatedEtablissementAlertesRouteImport
      parentRoute: typeof AuthenticatedEtablissementRoute
    }
    '/_authenticated/etablissement/classes': {
      id: '/_authenticated/etablissement/classes'
      path: '/classes'
      fullPath: '/etablissement/classes'
      preLoaderRoute: typeof AuthenticatedEtablissementClassesRouteImport
      parentRoute: typeof AuthenticatedEtablissementRoute
    }
    '/_authenticated/etablissement/composition': {
      id: '/_authenticated/etablissement/composition'
      path: '/composition'
      fullPath: '/etablissement/composition'
      preLoaderRoute: typeof AuthenticatedEtablissementCompositionRouteImport
      parentRoute: typeof AuthenticatedEtablissementRoute
    }
    '/_authenticated/etablissement/statistiques': {
      id: '/_authenticated/etablissement/statistiques'
      path: '/statistiques'
      fullPath: '/etablissement/statistiques'
      preLoaderRoute: typeof AuthenticatedEtablissementStatistiquesRouteImport
      parentRoute: typeof AuthenticatedEtablissementRoute
    }
    '/_authenticated/etablissement/utilisateurs': {
      id: '/_authenticated/etablissement/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/etablissement/utilisateurs'
      preLoaderRoute: typeof AuthenticatedEtablissementUtilisateursRouteImport
      parentRoute: typeof AuthenticatedEtablissementRoute
    }
    '/_authenticated/etablissement/validation-contenus': {
      id: '/_authenticated/etablissement/validation-contenus'
      path: '/validation-contenus'
      fullPath: '/etablissement/validation-contenus'
      preLoaderRoute: typeof AuthenticatedEtablissementValidationContenusRouteImport
      parentRoute: typeof AuthenticatedEtablissementRoute
    }
    '/_authenticated/etablissement/validation-enseignants': {
      id: '/_authenticated/etablissement/validation-enseignants'
      path: '/validation-enseignants'
      fullPath: '/etablissement/validation-enseignants'
      preLoaderRoute: typeof AuthenticatedEtablissementValidationEnseignantsRouteImport
      parentRoute: typeof AuthenticatedEtablissementRoute
    }
    '/_authenticated/etudiant/': {
      id: '/_authenticated/etudiant/'
      path: '/'
      fullPath: '/etudiant/'
      preLoaderRoute: typeof AuthenticatedEtudiantIndexRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/aide': {
      id: '/_authenticated/etudiant/aide'
      path: '/aide'
      fullPath: '/etudiant/aide'
      preLoaderRoute: typeof AuthenticatedEtudiantAideRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/classement': {
      id: '/_authenticated/etudiant/classement'
      path: '/classement'
      fullPath: '/etudiant/classement'
      preLoaderRoute: typeof AuthenticatedEtudiantClassementRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/cours': {
      id: '/_authenticated/etudiant/cours'
      path: '/cours'
      fullPath: '/etudiant/cours'
      preLoaderRoute: typeof AuthenticatedEtudiantCoursRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/defis': {
      id: '/_authenticated/etudiant/defis'
      path: '/defis'
      fullPath: '/etudiant/defis'
      preLoaderRoute: typeof AuthenticatedEtudiantDefisRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/historique': {
      id: '/_authenticated/etudiant/historique'
      path: '/historique'
      fullPath: '/etudiant/historique'
      preLoaderRoute: typeof AuthenticatedEtudiantHistoriqueRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/mediatheque': {
      id: '/_authenticated/etudiant/mediatheque'
      path: '/mediatheque'
      fullPath: '/etudiant/mediatheque'
      preLoaderRoute: typeof AuthenticatedEtudiantMediathequeRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/messages': {
      id: '/_authenticated/etudiant/messages'
      path: '/messages'
      fullPath: '/etudiant/messages'
      preLoaderRoute: typeof AuthenticatedEtudiantMessagesRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/notifications': {
      id: '/_authenticated/etudiant/notifications'
      path: '/notifications'
      fullPath: '/etudiant/notifications'
      preLoaderRoute: typeof AuthenticatedEtudiantNotificationsRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/parametres': {
      id: '/_authenticated/etudiant/parametres'
      path: '/parametres'
      fullPath: '/etudiant/parametres'
      preLoaderRoute: typeof AuthenticatedEtudiantParametresRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/representations': {
      id: '/_authenticated/etudiant/representations'
      path: '/representations'
      fullPath: '/etudiant/representations'
      preLoaderRoute: typeof AuthenticatedEtudiantRepresentationsRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/sujets': {
      id: '/_authenticated/etudiant/sujets'
      path: '/sujets'
      fullPath: '/etudiant/sujets'
      preLoaderRoute: typeof AuthenticatedEtudiantSujetsRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/enseignant/classes/': {
      id: '/_authenticated/enseignant/classes/'
      path: '/classes'
      fullPath: '/enseignant/classes/'
      preLoaderRoute: typeof AuthenticatedEnseignantClassesIndexRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/enseignant/classes/$classId': {
      id: '/_authenticated/enseignant/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/enseignant/classes/$classId'
      preLoaderRoute: typeof AuthenticatedEnseignantClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedEnseignantRoute
    }
    '/_authenticated/etudiant/cours/': {
      id: '/_authenticated/etudiant/cours/'
      path: '/'
      fullPath: '/etudiant/cours/'
      preLoaderRoute: typeof AuthenticatedEtudiantCoursIndexRouteImport
      parentRoute: typeof AuthenticatedEtudiantCoursRoute
    }
    '/_authenticated/etudiant/cours/$programmeId': {
      id: '/_authenticated/etudiant/cours/$programmeId'
      path: '/$programmeId'
      fullPath: '/etudiant/cours/$programmeId'
      preLoaderRoute: typeof AuthenticatedEtudiantCoursProgrammeIdRouteImport
      parentRoute: typeof AuthenticatedEtudiantCoursRoute
    }
    '/_authenticated/etudiant/examens/': {
      id: '/_authenticated/etudiant/examens/'
      path: '/examens'
      fullPath: '/etudiant/examens/'
      preLoaderRoute: typeof AuthenticatedEtudiantExamensIndexRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/examens/$examenId': {
      id: '/_authenticated/etudiant/examens/$examenId'
      path: '/examens/$examenId'
      fullPath: '/etudiant/examens/$examenId'
      preLoaderRoute: typeof AuthenticatedEtudiantExamensExamenIdRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/orientation/conseiller': {
      id: '/_authenticated/etudiant/orientation/conseiller'
      path: '/orientation/conseiller'
      fullPath: '/etudiant/orientation/conseiller'
      preLoaderRoute: typeof AuthenticatedEtudiantOrientationConseillerRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/orientation/filieres': {
      id: '/_authenticated/etudiant/orientation/filieres'
      path: '/orientation/filieres'
      fullPath: '/etudiant/orientation/filieres'
      preLoaderRoute: typeof AuthenticatedEtudiantOrientationFilieresRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
    '/_authenticated/etudiant/orientation/metiers': {
      id: '/_authenticated/etudiant/orientation/metiers'
      path: '/orientation/metiers'
      fullPath: '/etudiant/orientation/metiers'
      preLoaderRoute: typeof AuthenticatedEtudiantOrientationMetiersRouteImport
      parentRoute: typeof AuthenticatedEtudiantRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDemandesRoute: typeof AuthenticatedAdminDemandesRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDemandesRoute: AuthenticatedAdminDemandesRoute,
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEnseignantRouteChildren {
  AuthenticatedEnseignantEcoleRoute: typeof AuthenticatedEnseignantEcoleRoute
  AuthenticatedEnseignantElevesRoute: typeof AuthenticatedEnseignantElevesRoute
  AuthenticatedEnseignantExamensRoute: typeof AuthenticatedEnseignantExamensRoute
  AuthenticatedEnseignantMediathequeRoute: typeof AuthenticatedEnseignantMediathequeRoute
  AuthenticatedEnseignantMessagesRoute: typeof AuthenticatedEnseignantMessagesRoute
  AuthenticatedEnseignantNotificationsRoute: typeof AuthenticatedEnseignantNotificationsRoute
  AuthenticatedEnseignantParametresRoute: typeof AuthenticatedEnseignantParametresRoute
  AuthenticatedEnseignantSyllabusRoute: typeof AuthenticatedEnseignantSyllabusRoute
  AuthenticatedEnseignantIndexRoute: typeof AuthenticatedEnseignantIndexRoute
  AuthenticatedEnseignantClassesClassIdRoute: typeof AuthenticatedEnseignantClassesClassIdRoute
  AuthenticatedEnseignantClassesIndexRoute: typeof AuthenticatedEnseignantClassesIndexRoute
}

const AuthenticatedEnseignantRouteChildren: AuthenticatedEnseignantRouteChildren =
  {
    AuthenticatedEnseignantEcoleRoute: AuthenticatedEnseignantEcoleRoute,
    AuthenticatedEnseignantElevesRoute: AuthenticatedEnseignantElevesRoute,
    AuthenticatedEnseignantExamensRoute: AuthenticatedEnseignantExamensRoute,
    AuthenticatedEnseignantMediathequeRoute:
      AuthenticatedEnseignantMediathequeRoute,
    AuthenticatedEnseignantMessagesRoute: AuthenticatedEnseignantMessagesRoute,
    AuthenticatedEnseignantNotificationsRoute:
      AuthenticatedEnseignantNotificationsRoute,
    AuthenticatedEnseignantParametresRoute:
      AuthenticatedEnseignantParametresRoute,
    AuthenticatedEnseignantSyllabusRoute: AuthenticatedEnseignantSyllabusRoute,
    AuthenticatedEnseignantIndexRoute: AuthenticatedEnseignantIndexRoute,
    AuthenticatedEnseignantClassesClassIdRoute:
      AuthenticatedEnseignantClassesClassIdRoute,
    AuthenticatedEnseignantClassesIndexRoute:
      AuthenticatedEnseignantClassesIndexRoute,
  }

const AuthenticatedEnseignantRouteWithChildren =
  AuthenticatedEnseignantRoute._addFileChildren(
    AuthenticatedEnseignantRouteChildren,
  )

interface AuthenticatedEtablissementRouteChildren {
  AuthenticatedEtablissementAlertesRoute: typeof AuthenticatedEtablissementAlertesRoute
  AuthenticatedEtablissementClassesRoute: typeof AuthenticatedEtablissementClassesRoute
  AuthenticatedEtablissementCompositionRoute: typeof AuthenticatedEtablissementCompositionRoute
  AuthenticatedEtablissementStatistiquesRoute: typeof AuthenticatedEtablissementStatistiquesRoute
  AuthenticatedEtablissementUtilisateursRoute: typeof AuthenticatedEtablissementUtilisateursRoute
  AuthenticatedEtablissementValidationContenusRoute: typeof AuthenticatedEtablissementValidationContenusRoute
  AuthenticatedEtablissementValidationEnseignantsRoute: typeof AuthenticatedEtablissementValidationEnseignantsRoute
  AuthenticatedEtablissementIndexRoute: typeof AuthenticatedEtablissementIndexRoute
}

const AuthenticatedEtablissementRouteChildren: AuthenticatedEtablissementRouteChildren =
  {
    AuthenticatedEtablissementAlertesRoute:
      AuthenticatedEtablissementAlertesRoute,
    AuthenticatedEtablissementClassesRoute:
      AuthenticatedEtablissementClassesRoute,
    AuthenticatedEtablissementCompositionRoute:
      AuthenticatedEtablissementCompositionRoute,
    AuthenticatedEtablissementStatistiquesRoute:
      AuthenticatedEtablissementStatistiquesRoute,
    AuthenticatedEtablissementUtilisateursRoute:
      AuthenticatedEtablissementUtilisateursRoute,
    AuthenticatedEtablissementValidationContenusRoute:
      AuthenticatedEtablissementValidationContenusRoute,
    AuthenticatedEtablissementValidationEnseignantsRoute:
      AuthenticatedEtablissementValidationEnseignantsRoute,
    AuthenticatedEtablissementIndexRoute: AuthenticatedEtablissementIndexRoute,
  }

const AuthenticatedEtablissementRouteWithChildren =
  AuthenticatedEtablissementRoute._addFileChildren(
    AuthenticatedEtablissementRouteChildren,
  )

interface AuthenticatedEtudiantCoursRouteChildren {
  AuthenticatedEtudiantCoursProgrammeIdRoute: typeof AuthenticatedEtudiantCoursProgrammeIdRoute
  AuthenticatedEtudiantCoursIndexRoute: typeof AuthenticatedEtudiantCoursIndexRoute
}

const AuthenticatedEtudiantCoursRouteChildren: AuthenticatedEtudiantCoursRouteChildren =
  {
    AuthenticatedEtudiantCoursProgrammeIdRoute:
      AuthenticatedEtudiantCoursProgrammeIdRoute,
    AuthenticatedEtudiantCoursIndexRoute: AuthenticatedEtudiantCoursIndexRoute,
  }

const AuthenticatedEtudiantCoursRouteWithChildren =
  AuthenticatedEtudiantCoursRoute._addFileChildren(
    AuthenticatedEtudiantCoursRouteChildren,
  )

interface AuthenticatedEtudiantRouteChildren {
  AuthenticatedEtudiantAideRoute: typeof AuthenticatedEtudiantAideRoute
  AuthenticatedEtudiantClassementRoute: typeof AuthenticatedEtudiantClassementRoute
  AuthenticatedEtudiantCoursRoute: typeof AuthenticatedEtudiantCoursRouteWithChildren
  AuthenticatedEtudiantDefisRoute: typeof AuthenticatedEtudiantDefisRoute
  AuthenticatedEtudiantHistoriqueRoute: typeof AuthenticatedEtudiantHistoriqueRoute
  AuthenticatedEtudiantMediathequeRoute: typeof AuthenticatedEtudiantMediathequeRoute
  AuthenticatedEtudiantMessagesRoute: typeof AuthenticatedEtudiantMessagesRoute
  AuthenticatedEtudiantNotificationsRoute: typeof AuthenticatedEtudiantNotificationsRoute
  AuthenticatedEtudiantParametresRoute: typeof AuthenticatedEtudiantParametresRoute
  AuthenticatedEtudiantRepresentationsRoute: typeof AuthenticatedEtudiantRepresentationsRoute
  AuthenticatedEtudiantSujetsRoute: typeof AuthenticatedEtudiantSujetsRoute
  AuthenticatedEtudiantIndexRoute: typeof AuthenticatedEtudiantIndexRoute
  AuthenticatedEtudiantExamensExamenIdRoute: typeof AuthenticatedEtudiantExamensExamenIdRoute
  AuthenticatedEtudiantOrientationConseillerRoute: typeof AuthenticatedEtudiantOrientationConseillerRoute
  AuthenticatedEtudiantOrientationFilieresRoute: typeof AuthenticatedEtudiantOrientationFilieresRoute
  AuthenticatedEtudiantOrientationMetiersRoute: typeof AuthenticatedEtudiantOrientationMetiersRoute
  AuthenticatedEtudiantExamensIndexRoute: typeof AuthenticatedEtudiantExamensIndexRoute
}

const AuthenticatedEtudiantRouteChildren: AuthenticatedEtudiantRouteChildren = {
  AuthenticatedEtudiantAideRoute: AuthenticatedEtudiantAideRoute,
  AuthenticatedEtudiantClassementRoute: AuthenticatedEtudiantClassementRoute,
  AuthenticatedEtudiantCoursRoute: AuthenticatedEtudiantCoursRouteWithChildren,
  AuthenticatedEtudiantDefisRoute: AuthenticatedEtudiantDefisRoute,
  AuthenticatedEtudiantHistoriqueRoute: AuthenticatedEtudiantHistoriqueRoute,
  AuthenticatedEtudiantMediathequeRoute: AuthenticatedEtudiantMediathequeRoute,
  AuthenticatedEtudiantMessagesRoute: AuthenticatedEtudiantMessagesRoute,
  AuthenticatedEtudiantNotificationsRoute:
    AuthenticatedEtudiantNotificationsRoute,
  AuthenticatedEtudiantParametresRoute: AuthenticatedEtudiantParametresRoute,
  AuthenticatedEtudiantRepresentationsRoute:
    AuthenticatedEtudiantRepresentationsRoute,
  AuthenticatedEtudiantSujetsRoute: AuthenticatedEtudiantSujetsRoute,
  AuthenticatedEtudiantIndexRoute: AuthenticatedEtudiantIndexRoute,
  AuthenticatedEtudiantExamensExamenIdRoute:
    AuthenticatedEtudiantExamensExamenIdRoute,
  AuthenticatedEtudiantOrientationConseillerRoute:
    AuthenticatedEtudiantOrientationConseillerRoute,
  AuthenticatedEtudiantOrientationFilieresRoute:
    AuthenticatedEtudiantOrientationFilieresRoute,
  AuthenticatedEtudiantOrientationMetiersRoute:
    AuthenticatedEtudiantOrientationMetiersRoute,
  AuthenticatedEtudiantExamensIndexRoute:
    AuthenticatedEtudiantExamensIndexRoute,
}

const AuthenticatedEtudiantRouteWithChildren =
  AuthenticatedEtudiantRoute._addFileChildren(
    AuthenticatedEtudiantRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardEnseignantRoute: typeof AuthenticatedDashboardEnseignantRoute
  AuthenticatedDashboardEtudiantRoute: typeof AuthenticatedDashboardEtudiantRoute
  AuthenticatedEnseignantRoute: typeof AuthenticatedEnseignantRouteWithChildren
  AuthenticatedEtablissementRoute: typeof AuthenticatedEtablissementRouteWithChildren
  AuthenticatedEtudiantRoute: typeof AuthenticatedEtudiantRouteWithChildren
  AuthenticatedCoursesNewRoute: typeof AuthenticatedCoursesNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardEnseignantRoute: AuthenticatedDashboardEnseignantRoute,
  AuthenticatedDashboardEtudiantRoute: AuthenticatedDashboardEtudiantRoute,
  AuthenticatedEnseignantRoute: AuthenticatedEnseignantRouteWithChildren,
  AuthenticatedEtablissementRoute: AuthenticatedEtablissementRouteWithChildren,
  AuthenticatedEtudiantRoute: AuthenticatedEtudiantRouteWithChildren,
  AuthenticatedCoursesNewRoute: AuthenticatedCoursesNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CitoyenneteRoute: CitoyenneteRoute,
  CoursesRoute: CoursesRouteWithChildren,
  CultureRoute: CultureRoute,
  DemandeInscriptionRoute: DemandeInscriptionRoute,
  EducationRoute: EducationRoute,
  InscriptionRoute: InscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
